### ISSUE TITLE
Authorization header for hec_sender.py 

### ISSUE THREAD

**Issue by Humpelschnurz** [splunk/splunk-connect-for-snmp-traps#81]
Hi!

To make HEC accepting the data I added the authHeader line and the argument headers=authHeader to hec_sender.py:
```
       }
        **authHeader = {'Authorization': 'Splunk {}'.format('ace37efc-f19c-4e3f-b498-12345678)}** 
        try:
            session = self.get_session()
            response = session.post(url=self._endpoint, **headers=authHeader**, json=data)
            logger.debug(f"Response code is {response.status_code}")
        except requests.ConnectionError as e:
            logger.error(f"Connection error when sending data to HEC: {e}")
```

Might be also an idea to use the env variable SPLUNK_HEC_TOKEN as described in the readme

Cheers
Peter

**Comment by weliasz** [comment]
Trap does not need to set HEC token because it is sending data to OTEL collector which has Splunk HEC token configured.
