### ISSUE TITLE
self._endpoint in hec_sender.py is using OTEL_SERVER_URL

### ISSUE THREAD

**Issue by Humpelschnurz** [splunk/splunk-connect-for-snmp-traps#82]
Instead of "OTEL_SERVER_URL" it should be "SPLUNK_HEC_URL" to make it match readme instructions.
```
class HecSender:
    def __init__(self, args, server_config):
...
        self._endpoint = os.environ["OTEL_SERVER_URL"]
```

**Comment by weliasz** [comment]
Neither trap neither poller is sending data directly to Splunk. They send data to OTEL collector that later sends it to Splunk. 
So in this case trap needs OTEL endpoint not Splunk endpoint and this name is correct in this context. SPLUNK_HEC_URL from readme instructions is passed to OTEL.
